App\Entity\Location:
  properties:
    city:
      - NotBlank:
           groups: ['create', 'edit']

App\Entity\Measurement:
  properties:
    location:
      - NotBlank:
          groups: [ 'create', 'edit' ]

App\Form\Location:
  properties:
    city:
      - NotBlank:
          groups: ['create', 'edit']
